# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecsgo < Formula
  desc "Interactive CLI tool which acts as a wrapper around the ECS ExecuteCommand API."
  homepage ""
  version "0.3.0"
  license "Apache2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tedsmitt/ecsgo/releases/download/0.3.0/ecsgo_Darwin_arm64.tar.gz"
      sha256 "f68915f090fcce012cfa479526b84e381d7770db329251afb9ee2433da21d992"

      def install
        bin.install "ecsgo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tedsmitt/ecsgo/releases/download/0.3.0/ecsgo_Darwin_x86_64.tar.gz"
      sha256 "24278ab8eafd0342d5e64acb384bfc41b5f819545a5e0e94b48c3891e32bfa01"

      def install
        bin.install "ecsgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tedsmitt/ecsgo/releases/download/0.3.0/ecsgo_Linux_x86_64.tar.gz"
      sha256 "cd96d11529df6387f310ad43b65dd5437da60c044ec5ba8862df62b06ae7e5b4"

      def install
        bin.install "ecsgo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tedsmitt/ecsgo/releases/download/0.3.0/ecsgo_Linux_arm64.tar.gz"
      sha256 "56032fbd6e1a44a8fa52b206d578b72712ec966fa5229bd2340d01bb6e12777f"

      def install
        bin.install "ecsgo"
      end
    end
  end

  depends_on "go"

  test do
    system "#{bin}/goreleaser -v"
  end
end
